# In this file for keys camel case is being used
apiVersion: apps/v1
kind: Deployment # this is the object type
metadata:
  name: client-deployment #thisis the object name
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000